### PR TITLE
Update `benchmark:pdfium_get_text()` to new pypdfium2 API

### PR DESCRIPTION
**Pull request by mara004**
This patch would port the benchmark code to pypdfium2's new API. Version 2.0.0 is not actually released yet, but I plan to make it available soon.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you for the PR! Then I'll wait with merging when 2.0.0 is released :-)

**Comment by mara004** [comment]
Version 2.0.0 is released now.

**Comment by mara004** [comment]
Oh, I see I forgot to update the release date, sorry. Can you please change `2022-06-??` to `2022-06-09` in main?

**Comment by MartinThoma** [comment]
Sure - it's already done :-) Thank you for the comment :-)

**Comment by mara004** [comment]
Thanks!

**Pull request merged**
